// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol/Snapshot/SnapshotStateMachine.proto

#ifndef PROTOBUF_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto__INCLUDED
#define PROTOBUF_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Protocol/Client/Client.pb.h"
// @@protoc_insertion_point(includes)

namespace LogCabin {
namespace Server {
namespace SnapshotStateMachine {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
void protobuf_AssignDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
void protobuf_ShutdownFile_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();

class VersionUpdate;
class Session;
class Response;
class Header;

// ===================================================================

class VersionUpdate : public ::google::protobuf::Message {
 public:
  VersionUpdate();
  virtual ~VersionUpdate();

  VersionUpdate(const VersionUpdate& from);

  inline VersionUpdate& operator=(const VersionUpdate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VersionUpdate& default_instance();

  void Swap(VersionUpdate* other);

  // implements Message ----------------------------------------------

  VersionUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VersionUpdate& from);
  void MergeFrom(const VersionUpdate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 log_index = 1;
  inline bool has_log_index() const;
  inline void clear_log_index();
  static const int kLogIndexFieldNumber = 1;
  inline ::google::protobuf::uint64 log_index() const;
  inline void set_log_index(::google::protobuf::uint64 value);

  // required uint32 version = 2;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 2;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:LogCabin.Server.SnapshotStateMachine.VersionUpdate)
 private:
  inline void set_has_log_index();
  inline void clear_has_log_index();
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 log_index_;
  ::google::protobuf::uint32 version_;
  friend void  protobuf_AddDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_AssignDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();

  void InitAsDefaultInstance();
  static VersionUpdate* default_instance_;
};
// -------------------------------------------------------------------

class Session : public ::google::protobuf::Message {
 public:
  Session();
  virtual ~Session();

  Session(const Session& from);

  inline Session& operator=(const Session& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Session& default_instance();

  void Swap(Session* other);

  // implements Message ----------------------------------------------

  Session* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Session& from);
  void MergeFrom(const Session& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 client_id = 1;
  inline bool has_client_id() const;
  inline void clear_client_id();
  static const int kClientIdFieldNumber = 1;
  inline ::google::protobuf::uint64 client_id() const;
  inline void set_client_id(::google::protobuf::uint64 value);

  // required uint64 last_modified = 2;
  inline bool has_last_modified() const;
  inline void clear_last_modified();
  static const int kLastModifiedFieldNumber = 2;
  inline ::google::protobuf::uint64 last_modified() const;
  inline void set_last_modified(::google::protobuf::uint64 value);

  // required uint64 first_outstanding_rpc = 3;
  inline bool has_first_outstanding_rpc() const;
  inline void clear_first_outstanding_rpc();
  static const int kFirstOutstandingRpcFieldNumber = 3;
  inline ::google::protobuf::uint64 first_outstanding_rpc() const;
  inline void set_first_outstanding_rpc(::google::protobuf::uint64 value);

  // repeated .LogCabin.Server.SnapshotStateMachine.Response rpc_response = 4;
  inline int rpc_response_size() const;
  inline void clear_rpc_response();
  static const int kRpcResponseFieldNumber = 4;
  inline const ::LogCabin::Server::SnapshotStateMachine::Response& rpc_response(int index) const;
  inline ::LogCabin::Server::SnapshotStateMachine::Response* mutable_rpc_response(int index);
  inline ::LogCabin::Server::SnapshotStateMachine::Response* add_rpc_response();
  inline const ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Response >&
      rpc_response() const;
  inline ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Response >*
      mutable_rpc_response();

  // @@protoc_insertion_point(class_scope:LogCabin.Server.SnapshotStateMachine.Session)
 private:
  inline void set_has_client_id();
  inline void clear_has_client_id();
  inline void set_has_last_modified();
  inline void clear_has_last_modified();
  inline void set_has_first_outstanding_rpc();
  inline void clear_has_first_outstanding_rpc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 client_id_;
  ::google::protobuf::uint64 last_modified_;
  ::google::protobuf::uint64 first_outstanding_rpc_;
  ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Response > rpc_response_;
  friend void  protobuf_AddDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_AssignDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();

  void InitAsDefaultInstance();
  static Session* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 rpc_number = 1;
  inline bool has_rpc_number() const;
  inline void clear_rpc_number();
  static const int kRpcNumberFieldNumber = 1;
  inline ::google::protobuf::uint64 rpc_number() const;
  inline void set_rpc_number(::google::protobuf::uint64 value);

  // required .LogCabin.Protocol.Client.StateMachineCommand.Response response = 2;
  inline bool has_response() const;
  inline void clear_response();
  static const int kResponseFieldNumber = 2;
  inline const ::LogCabin::Protocol::Client::StateMachineCommand_Response& response() const;
  inline ::LogCabin::Protocol::Client::StateMachineCommand_Response* mutable_response();
  inline ::LogCabin::Protocol::Client::StateMachineCommand_Response* release_response();
  inline void set_allocated_response(::LogCabin::Protocol::Client::StateMachineCommand_Response* response);

  // @@protoc_insertion_point(class_scope:LogCabin.Server.SnapshotStateMachine.Response)
 private:
  inline void set_has_rpc_number();
  inline void clear_has_rpc_number();
  inline void set_has_response();
  inline void clear_has_response();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 rpc_number_;
  ::LogCabin::Protocol::Client::StateMachineCommand_Response* response_;
  friend void  protobuf_AddDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_AssignDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// -------------------------------------------------------------------

class Header : public ::google::protobuf::Message {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  Header* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .LogCabin.Server.SnapshotStateMachine.VersionUpdate version_update = 1;
  inline int version_update_size() const;
  inline void clear_version_update();
  static const int kVersionUpdateFieldNumber = 1;
  inline const ::LogCabin::Server::SnapshotStateMachine::VersionUpdate& version_update(int index) const;
  inline ::LogCabin::Server::SnapshotStateMachine::VersionUpdate* mutable_version_update(int index);
  inline ::LogCabin::Server::SnapshotStateMachine::VersionUpdate* add_version_update();
  inline const ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::VersionUpdate >&
      version_update() const;
  inline ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::VersionUpdate >*
      mutable_version_update();

  // repeated .LogCabin.Server.SnapshotStateMachine.Session session = 2;
  inline int session_size() const;
  inline void clear_session();
  static const int kSessionFieldNumber = 2;
  inline const ::LogCabin::Server::SnapshotStateMachine::Session& session(int index) const;
  inline ::LogCabin::Server::SnapshotStateMachine::Session* mutable_session(int index);
  inline ::LogCabin::Server::SnapshotStateMachine::Session* add_session();
  inline const ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Session >&
      session() const;
  inline ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Session >*
      mutable_session();

  // @@protoc_insertion_point(class_scope:LogCabin.Server.SnapshotStateMachine.Header)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::VersionUpdate > version_update_;
  ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Session > session_;
  friend void  protobuf_AddDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_AssignDesc_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto();

  void InitAsDefaultInstance();
  static Header* default_instance_;
};
// ===================================================================


// ===================================================================

// VersionUpdate

// required uint64 log_index = 1;
inline bool VersionUpdate::has_log_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VersionUpdate::set_has_log_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VersionUpdate::clear_has_log_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VersionUpdate::clear_log_index() {
  log_index_ = GOOGLE_ULONGLONG(0);
  clear_has_log_index();
}
inline ::google::protobuf::uint64 VersionUpdate::log_index() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.VersionUpdate.log_index)
  return log_index_;
}
inline void VersionUpdate::set_log_index(::google::protobuf::uint64 value) {
  set_has_log_index();
  log_index_ = value;
  // @@protoc_insertion_point(field_set:LogCabin.Server.SnapshotStateMachine.VersionUpdate.log_index)
}

// required uint32 version = 2;
inline bool VersionUpdate::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VersionUpdate::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VersionUpdate::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VersionUpdate::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 VersionUpdate::version() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.VersionUpdate.version)
  return version_;
}
inline void VersionUpdate::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:LogCabin.Server.SnapshotStateMachine.VersionUpdate.version)
}

// -------------------------------------------------------------------

// Session

// required uint64 client_id = 1;
inline bool Session::has_client_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Session::set_has_client_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Session::clear_has_client_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Session::clear_client_id() {
  client_id_ = GOOGLE_ULONGLONG(0);
  clear_has_client_id();
}
inline ::google::protobuf::uint64 Session::client_id() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Session.client_id)
  return client_id_;
}
inline void Session::set_client_id(::google::protobuf::uint64 value) {
  set_has_client_id();
  client_id_ = value;
  // @@protoc_insertion_point(field_set:LogCabin.Server.SnapshotStateMachine.Session.client_id)
}

// required uint64 last_modified = 2;
inline bool Session::has_last_modified() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Session::set_has_last_modified() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Session::clear_has_last_modified() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Session::clear_last_modified() {
  last_modified_ = GOOGLE_ULONGLONG(0);
  clear_has_last_modified();
}
inline ::google::protobuf::uint64 Session::last_modified() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Session.last_modified)
  return last_modified_;
}
inline void Session::set_last_modified(::google::protobuf::uint64 value) {
  set_has_last_modified();
  last_modified_ = value;
  // @@protoc_insertion_point(field_set:LogCabin.Server.SnapshotStateMachine.Session.last_modified)
}

// required uint64 first_outstanding_rpc = 3;
inline bool Session::has_first_outstanding_rpc() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Session::set_has_first_outstanding_rpc() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Session::clear_has_first_outstanding_rpc() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Session::clear_first_outstanding_rpc() {
  first_outstanding_rpc_ = GOOGLE_ULONGLONG(0);
  clear_has_first_outstanding_rpc();
}
inline ::google::protobuf::uint64 Session::first_outstanding_rpc() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Session.first_outstanding_rpc)
  return first_outstanding_rpc_;
}
inline void Session::set_first_outstanding_rpc(::google::protobuf::uint64 value) {
  set_has_first_outstanding_rpc();
  first_outstanding_rpc_ = value;
  // @@protoc_insertion_point(field_set:LogCabin.Server.SnapshotStateMachine.Session.first_outstanding_rpc)
}

// repeated .LogCabin.Server.SnapshotStateMachine.Response rpc_response = 4;
inline int Session::rpc_response_size() const {
  return rpc_response_.size();
}
inline void Session::clear_rpc_response() {
  rpc_response_.Clear();
}
inline const ::LogCabin::Server::SnapshotStateMachine::Response& Session::rpc_response(int index) const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Session.rpc_response)
  return rpc_response_.Get(index);
}
inline ::LogCabin::Server::SnapshotStateMachine::Response* Session::mutable_rpc_response(int index) {
  // @@protoc_insertion_point(field_mutable:LogCabin.Server.SnapshotStateMachine.Session.rpc_response)
  return rpc_response_.Mutable(index);
}
inline ::LogCabin::Server::SnapshotStateMachine::Response* Session::add_rpc_response() {
  // @@protoc_insertion_point(field_add:LogCabin.Server.SnapshotStateMachine.Session.rpc_response)
  return rpc_response_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Response >&
Session::rpc_response() const {
  // @@protoc_insertion_point(field_list:LogCabin.Server.SnapshotStateMachine.Session.rpc_response)
  return rpc_response_;
}
inline ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Response >*
Session::mutable_rpc_response() {
  // @@protoc_insertion_point(field_mutable_list:LogCabin.Server.SnapshotStateMachine.Session.rpc_response)
  return &rpc_response_;
}

// -------------------------------------------------------------------

// Response

// required uint64 rpc_number = 1;
inline bool Response::has_rpc_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_rpc_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_rpc_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_rpc_number() {
  rpc_number_ = GOOGLE_ULONGLONG(0);
  clear_has_rpc_number();
}
inline ::google::protobuf::uint64 Response::rpc_number() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Response.rpc_number)
  return rpc_number_;
}
inline void Response::set_rpc_number(::google::protobuf::uint64 value) {
  set_has_rpc_number();
  rpc_number_ = value;
  // @@protoc_insertion_point(field_set:LogCabin.Server.SnapshotStateMachine.Response.rpc_number)
}

// required .LogCabin.Protocol.Client.StateMachineCommand.Response response = 2;
inline bool Response::has_response() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_response() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_response() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_response() {
  if (response_ != NULL) response_->::LogCabin::Protocol::Client::StateMachineCommand_Response::Clear();
  clear_has_response();
}
inline const ::LogCabin::Protocol::Client::StateMachineCommand_Response& Response::response() const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Response.response)
  return response_ != NULL ? *response_ : *default_instance_->response_;
}
inline ::LogCabin::Protocol::Client::StateMachineCommand_Response* Response::mutable_response() {
  set_has_response();
  if (response_ == NULL) response_ = new ::LogCabin::Protocol::Client::StateMachineCommand_Response;
  // @@protoc_insertion_point(field_mutable:LogCabin.Server.SnapshotStateMachine.Response.response)
  return response_;
}
inline ::LogCabin::Protocol::Client::StateMachineCommand_Response* Response::release_response() {
  clear_has_response();
  ::LogCabin::Protocol::Client::StateMachineCommand_Response* temp = response_;
  response_ = NULL;
  return temp;
}
inline void Response::set_allocated_response(::LogCabin::Protocol::Client::StateMachineCommand_Response* response) {
  delete response_;
  response_ = response;
  if (response) {
    set_has_response();
  } else {
    clear_has_response();
  }
  // @@protoc_insertion_point(field_set_allocated:LogCabin.Server.SnapshotStateMachine.Response.response)
}

// -------------------------------------------------------------------

// Header

// repeated .LogCabin.Server.SnapshotStateMachine.VersionUpdate version_update = 1;
inline int Header::version_update_size() const {
  return version_update_.size();
}
inline void Header::clear_version_update() {
  version_update_.Clear();
}
inline const ::LogCabin::Server::SnapshotStateMachine::VersionUpdate& Header::version_update(int index) const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Header.version_update)
  return version_update_.Get(index);
}
inline ::LogCabin::Server::SnapshotStateMachine::VersionUpdate* Header::mutable_version_update(int index) {
  // @@protoc_insertion_point(field_mutable:LogCabin.Server.SnapshotStateMachine.Header.version_update)
  return version_update_.Mutable(index);
}
inline ::LogCabin::Server::SnapshotStateMachine::VersionUpdate* Header::add_version_update() {
  // @@protoc_insertion_point(field_add:LogCabin.Server.SnapshotStateMachine.Header.version_update)
  return version_update_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::VersionUpdate >&
Header::version_update() const {
  // @@protoc_insertion_point(field_list:LogCabin.Server.SnapshotStateMachine.Header.version_update)
  return version_update_;
}
inline ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::VersionUpdate >*
Header::mutable_version_update() {
  // @@protoc_insertion_point(field_mutable_list:LogCabin.Server.SnapshotStateMachine.Header.version_update)
  return &version_update_;
}

// repeated .LogCabin.Server.SnapshotStateMachine.Session session = 2;
inline int Header::session_size() const {
  return session_.size();
}
inline void Header::clear_session() {
  session_.Clear();
}
inline const ::LogCabin::Server::SnapshotStateMachine::Session& Header::session(int index) const {
  // @@protoc_insertion_point(field_get:LogCabin.Server.SnapshotStateMachine.Header.session)
  return session_.Get(index);
}
inline ::LogCabin::Server::SnapshotStateMachine::Session* Header::mutable_session(int index) {
  // @@protoc_insertion_point(field_mutable:LogCabin.Server.SnapshotStateMachine.Header.session)
  return session_.Mutable(index);
}
inline ::LogCabin::Server::SnapshotStateMachine::Session* Header::add_session() {
  // @@protoc_insertion_point(field_add:LogCabin.Server.SnapshotStateMachine.Header.session)
  return session_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Session >&
Header::session() const {
  // @@protoc_insertion_point(field_list:LogCabin.Server.SnapshotStateMachine.Header.session)
  return session_;
}
inline ::google::protobuf::RepeatedPtrField< ::LogCabin::Server::SnapshotStateMachine::Session >*
Header::mutable_session() {
  // @@protoc_insertion_point(field_mutable_list:LogCabin.Server.SnapshotStateMachine.Header.session)
  return &session_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SnapshotStateMachine
}  // namespace Server
}  // namespace LogCabin

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Protocol_2fSnapshot_2fSnapshotStateMachine_2eproto__INCLUDED
